### ISSUE TITLE
the given client credentials were not valid

### ISSUE THREAD

**Issue by leonardshackelford** [adplabs/adp-connection-NET#10]
Greetings Team, I downloaded sample .NET code.  I am able to connect to test instances (iat...) without issue.  I have updated the configuration file with appropriate values for connecting to production.  See scrubbed configuration data below.  The error message I'm getting is 'The give client credentials were not valid'.  

There are several components to 'credentials'.  For example, there is clientID, clientSecret, Certificate, and key.  How do I know which piece is causing problem.  I have confirmed the clientID and secret with ADP representative.  That team member indicated they can't support the .net sample code and I should post the question here.

Can a team member confirm the URL's below look right?
I should be using the .pfx not .pem file correct?
My company has the work force now (WFN) product.  Does the sample code provided work with WFN?

{
  "clientID": "99999999-9999-9999-9999-999999999999",
  "clientSecret": "99999999-9999-9999-9999-999999999999",
  "sslCertPath": "..\\..\\Content\\certs\\6eb01e6b-a71a-44e2-84a0-d313edd6747d.pfx",
  "sslKeyPath": "..\\..\\Content\\certs\\{mycompanyname}_auth.key",
  "tokenServerURL": "https://api.adp.com/auth/oauth/v2/token",
  "disconnectURL": "https://accounts.adp.com/auth/oauth/v2/logout",
  "apiRequestURL": "https://api.adp.com",
  "responseType": "code",
  "defaultexpiration": 3600,
  "grantType": "client_credentials"
}

**Comment by ADPMarketplace** [comment]
Hi,

1. Please use the following end point for the "tokenServerURL" - "https://accounts.adp.com/auth/oauth/v2/token"
2. We see that the sslKeyPass is missing in the config properties. You should be using the .pfx file along with the PASSWORD (sslKeyPass) for the given certificate . For reference please go through the following link. https://developers.adp.com/articles/guides/build-dataConn-app-w-dev-lib-dotNET
3. Yes the sample code works for WFN as well provided you are sending all the valid details which include - Client ID, Client Secret, Certificate and Certificate Password.

Thanks,
Kirthi Priya Debbadi.

**Comment by leonardshackelford** [comment]
Greetings Kirthi,

Thank you for your feedback.  I have updated the "tokenServerURL" as requested.
When creating the CSR, we left the challenge password blank (as suggested in our ADP document).  Is the sslKeyPass a required field?

I've tried to connect again after updating the tokenServerURL.  I do not have an sslKeyPass.  I get the error message "proper client ssl certificate was not presented".  This is the pfx that was created using our PEM file.  I am able to connect to ADP API's using postman which uses the .pem and .key files.

{
"clientID": "99999999-9999-9999-9999-999999999999",
"clientSecret": "99999999-9999-9999-9999-999999999999",
"sslCertPath": "..\..\Content\certs\6eb01e6b-a71a-44e2-84a0-d313edd6747d.pfx",
"sslKeyPath": "..\..\Content\certs\{mycompanyname}_auth.key",
"tokenServerURL": "https://accounts.adp.com/auth/oauth/v2/token",
"disconnectURL": "https://accounts.adp.com/auth/oauth/v2/logout",
"apiRequestURL": "https://api.adp.com",
"responseType": "code",
"defaultexpiration": 3600,
"grantType": "client_credentials"
}

**Comment by ADPMarketplace** [comment]
Hi,

Yes, sslKeyPass is mandatory field. But it is not something related to CSR, during the pfx conversion from PEM file you must have set the PFX password( i.e nothing but sslKeyPass).

Can you try passing the sslKeyPass field.

Thanks,
Sruthi

**Comment by gHoodlum** [comment]
Did this finally fix the issue? I am having exactly the same problem even after sending in the sslKeyPass.

**Comment by migdiada** [comment]
Sending the SSL cert and key on every call resolved the issue I was having.

**Comment by gHoodlum** [comment]
Are you using the adp-connection-NET library and sending the PFX cert?

**Comment by migdiada** [comment]
I was using python. Apologies.
