### ISSUE TITLE
Connection worked on localserver but not when pushed to live

### ISSUE THREAD

**Issue by amitabgwebs** [adplabs/adp-connection-NET#12]
Hi Team,

Thanks for providing this library which helps in connecting with ADP.  I am using this code

```
            string clientconfig = @"{
               ""clientID"":       ""xxxxxxxx"",
               ""clientSecret"":   ""xxxxxxxx"",
               ""sslCertPath"":    ""~/Content/certs/Pxxxxxxxx.pfx"",
               ""sslKeyPath"":     ""~/Content/certs/xxxxxxxx_auth.key"",
               ""sslKeyPass"":     ""xxxxxxxx"",
               ""tokenServerURL"": ""https://iat-accounts.adp.com/auth/oauth/v2/token"",
            ""grantType"":      ""client_credentials""
               }";
```
Which works successfully in local-server and I am getting back "Token" but when I push same code on server I am not getting "Token" instead getting "One or more errors occurred". Can you guide me what I am missing here when trying this code on server.

Thanks

**Comment by ADPMarketplace** [comment]
Hi,

Can you please confirm that the certificates you are using to make the below call belong to Production Environment? The certificate that is present on the ADP library cannot be used for production environment and are meant only for the sandbox.

Thanks,
Kirthi Priya Debbadi.

**Comment by amitabgwebs** [comment]
Hi,

Thanks for reply!
Ok, I will check it and confirm.

Also, I am not able to use post request using this library. Can you provide me code for POST request?

**Comment by ADPMarketplace** [comment]
Hi,

Could you please let us know regarding where exactly you are finding difficulty in using the POST request. Have you been receiving any error?

**Comment by amitabgwebs** [comment]
I am following ADPClientWebDemo. Found this code for GET request
var data = connection.getADPData("REQUEST_URL");

But for POST request not found any code. Is there any method available for the same?

I see :
postADPEvent is available in https://github.com/adplabs/adp-connection-NET/blob/master/ADPClient/Connection/ADPApiConnection.cs

Which is what I am looking for. But not able to use this from the project after installing package "ADP-library-connection-NET". 

![image](https://user-images.githubusercontent.com/23099781/42759749-b97ca7e8-8925-11e8-9f29-c76347946035.png)

Is "postADPEvent" method available or not? If yes how I can use? If not should I have to create own method for POST query?

**Comment by ADPMarketplace** [comment]
Hi,

The postADPEvent method is available in ADPApiConnection.cs file. This method can be used by creating an action. Please find the attached screenshot.

**Comment by amitabgwebs** [comment]
Not able to see any attachment. Can you please attach it again?

**Comment by amitabgwebs** [comment]
I found my mistake.

Thanks Kirthi!

**Comment by ADPMarketplace** [comment]
You're welcome!

Thanks,
Kirthi Priya Debbadi.
