### ISSUE TITLE
Connection Exception: Unauthorized???

### ISSUE THREAD

**Issue by EducationalInquiry** [adplabs/adp-connection-NET#14]
I try to compile and I keep getting the following error:

Connection Exception: Unauthorized: {
  "error": "invalid_request",
  "error_description": "proper client ssl certificate was not presented"
}
The program '[13812] ADPClientDemo.exe' has exited with code 0 (0x0).

Suggestions?

**Comment by ADPMarketplace** [comment]
Hi,
Could you please check if you're providing SSL certificate properly or not? May be the path where you have placed the certificates is not getting picked up by your code or you're not presenting the valid certificates. Please recheck these points once.

If you're still facing the issue, please provide us more details which will help us debug further. For Ex, ADP transaction IDs, Client Name, Client ID certificates that you're using (if possible), we'd like to check at our end. Please send us a separate email to "partnersupport@adpmarketplace.zendesk.com" when you're sending the certificates


Thanks,
Mahesh

**Comment by EducationalInquiry** [comment]
Hi, Mahesh,
Thank you for your quick reply.  

Honestly, I made no modifications to the code.  I’m only trying to run a test via the certs that were included in the repo (i.e. **adp-connection-NET-master\ADPClientDemo\Content\certs**) to see if I could get that to work/compile.

I believe one of the certs is expired and I was wondering if I could acquire one that is valid to allow for the example program in the repo to work.

Let me know what you think when you can.  In the meantime, I’ll see if I can get you a screenshot.  
Thanks!

**Comment by ADPMarketplace** [comment]
Hi,
We'll reverify the certs once. But if you've made a call to ADP systems, then you should have received a transaction\correlation ID from ADP systems. Could you please share the same with us?

Thanks,
Mahesh

**Comment by EducationalInquiry** [comment]
GM, Mahesh,
I’d be happy to provide any info I can to help resolve the issue.  Where can I find a transaction\correlation ID?  When would I have received this as the program was being ran/compiled?  

Also, are there any logs that I can provide to you that would be of help?  Thanks!

**Comment by ADPMarketplace** [comment]
Hi,
We've downloaded the latest code(today's code whatever is there on the developer portal) and ran in our system and it ran successfully without any issue.

We tested both "Using .NET Developer Libraries to Build an End-User Application" and "Using .NET Developer Libraries to Build a Data Connector Application" and both of them are able to connect to ADP system and get the access token.

Note: Please make sure that the application is running on the port # 8889 and there should not be any other application running on this port.

If you're facing the issue again, please record a video of end to end steps performed by you and share with us. Please share with us the certificates( copy from your code ) and client details and the session ID\transaction ID you've received from ADP.

If the issue still doesn't get resolved, we will have a call to debug the issue. Expecting the response asap.

Thanks,
Mahesh

**Comment by EducationalInquiry** [comment]
Hi, Mahesh,

After some research on my part yesterday, I learned that the reason for this failure was due to a security/filtering appliance on my end.  It was strange b/c all of my Postman calls to ADP worked fine (???) from a test workstation I was using.  However, my network admin needed to make some adjustments and everything is compiling as expected.    Please forgive me for any inconvenience.  Thanks again for your help/suggestions!

**Comment by ADPMarketplace** [comment]
Hi,
It's my pleasure to help you. Please don't hesitate to come back to us if you face the issue again. We're here to help you.

Thanks,
Mahesh

**Comment by awdee** [comment]
Hi, 

I also experience this error with the current source. May I know if it's working on your end.

Thanks

**Comment by awdee** [comment]
Can we open this thread? Thanks.

**Comment by inimist** [comment]
Hi EducationalInquiry, 

Do you know what changes your server admin had to make in order to make it working? I am having same issue here. ADP API calls work just fine on my macbook localhost website and it does also in Postman but when I try to run it on my server on Azure it fails for the error 

```
{
  "error": "invalid_request",
  "error_description": "proper client ssl certificate was not presented"
}'
```

I am not sure what are the next steps to fix this nasty error. I am struggling for last 3 days.

**Comment by inimist** [comment]
If there is any help offered from ADP community on this issue I'll feel obliged.

**Comment by gregarican** [comment]
If you search the open and closed issues on this GitHub project page you will find plenty of references to potential root causes of what you are seeing. Basically a combination of ensuring your client is at least using TLS 1.2, ensuring you have a properly deployed SSL certificate, ensuring that any ADP certs are current, etc. I'd suggest searching here and trying some of these angles.

**Comment by inimist** [comment]
Thanks @gregarican, I am trying
