### ISSUE TITLE
ADPClientDemo postADPEvent Forbidden

### ISSUE THREAD

**Issue by bpautsch** [adplabs/adp-connection-NET#16]
Thanks for the demo apps. They help clarify a lot.

I have the Web SSO working (ADPClientWebDemo) and have moved onto the Data Connector (ADPClientDemo). I'm using the sample code. It authenticates and gets a token, but when it tries to get data with code "var eventsResults = connection.postADPEvent(eventsUrl, eventsBody);", it returns the error below. 

Any ideas? Do I need to specify "accessScope" in the client config?
Thanks for your help.

ADPClient.ADPException.ADPConnectionException: 
**Connection Exception: Forbidden:**
{
   "confirmMessage":{
      "confirmMessageID":{
         "idValue":"70b6e7d7-66e5-4a75-b08f-170d805e10df",
         "schemeName":"confirmMessageID",
         "schemeAgencyName":"Marketplace"
      },
      "createDateTime":"2018-08-04T13:40:43.211Z",
      "protocolStatusCode":{
         "codeValue":403
      },
      "protocolCode":{
         "codeValue":"http"
      },
      "requestStatusCode":{
         "codeValue":"failed"
      },
      "requestMethodCode":{
         "codeValue":"POST"
      },
      "sessionID":{
         "idValue":"g+EMiD2r2xeNuVDr2YdY2DnLUpc=",
         "schemeName":"sessionID",
         "schemeAgencyName":"Marketplace"
      },
      "requestLink":{
         "href":"/events/core/v1/consumer-application-subscription-credentials.read",
         "rel":"related",
         "method":"POST"
      },
   }
}

**Comment by ADPMarketplace** [comment]
Hi,
Sorry for the inconvenience caused to you.
This is something related to permission issue and so we'd need a couple of details from you. Could you please share the correlation ID\ transaction ID that you've received from ADP along with the client details you're using and end to end screenshots\videos of the steps performed by you.

Thanks,
Mahesh

**Comment by bpautsch** [comment]
I'm using the config in your app. Your sample credentials, keys, certs, etc.
I downloaded the project, uncommented this code in ADPClientDemo > Program.cs:
                        var eventsUrl = "/events/core/v1/consumer-application-subscription-credentials.read";
                        var eventsBody = "{\"events\": [{}]}";
                        var eventsResults = connection.postADPEvent(eventsUrl, eventsBody);
                        Console.WriteLine("\r\nEvents Data: {0} ", eventsResults);
                        String str = connection.getADPData("/hr/v2/workers?limit=5");
                        Console.WriteLine("\r\nData: {0} ", str);

And ran the application. The code connects and gets a token, but it errors on this line:
                        var eventsResults = connection.postADPEvent(eventsUrl, eventsBody);

Please try testing with the sample app. It should fail for you too.

**Comment by ADPMarketplace** [comment]
We're working on this. Will get back to you with the update.

**Comment by ADPMarketplace** [comment]
Hi,
We're yet to get update.

Thanks,
Mahesh

**Comment by awdee** [comment]
Hello,

I also encounter this error ? Any update to this matter?

Thanks

**Comment by ADPMarketplace** [comment]
Awdee -

The test client credentials will not work with the sample event commented in sample app.  That particular event requires a different set of credentials.  We will take a look at providing a different event in the code to avoid confusion.  

Thanks,

Wesley
