### ISSUE TITLE
proper client ssl certificate was not presented

### ISSUE THREAD

**Issue by awdee** [adplabs/adp-connection-NET#17]
I try to compile the latest source code and get this error. 

Connection Exception: Unauthorized: {
"error": "invalid_request",
"error_description": "proper client ssl certificate was not presented"
}

Thanks

**Comment by ADPMarketplace** [comment]
Hi,

For which client is this issue is coming ?

Thanks,
Sruthi

**Comment by awdee** [comment]
Hi Sruthi, 

I'm just using the provided source code to test the connection. Is the provided certificate expired or demographic restriction ?

Thanks/

**Comment by awdee** [comment]
Hi Sruthi,

I'm just using the provided source code to test the connection. Is the provided certificate expired or demographic restriction ?

Thanks

**Comment by gregarican** [comment]
In your source code, are you explicitly requesting TLS 1.2? If you are requesting a lower TLS version perhaps that is the issue?

**Comment by ADPMarketplace** [comment]
Are you using the same consumerapp Id which is there in the source code or changing with other ? By below error we see is clearly related to certificate issue. 

Thanks,
Sruthi

**Comment by awdee** [comment]
Hello @gregarican I'm running it in visual studio 2015 on windows 8.1.
Hello @ADPMarketplace - Sruthi, i'm using the consumerapp id the source code provided, no modification in source code.

Thanks

**Comment by awdee** [comment]
Hello @gregarican , I verified and i'm requesting using TLS 1.2.

**Comment by awdee** [comment]
Hello @ADPMarketplace - Sruthi, is the clientid you we're asking?

**Comment by ADPMarketplace** [comment]
Hi,

Can you please share the correlation ID of the failed API. Correlation ID will be received in the response headers of API Response.

Thanks,
Sruthi

**Comment by awdee** [comment]
Hi @ADPMarketplace - Sruthi,

Where can I find the correlation ID? 

Thanks

**Comment by ADPMarketplace** [comment]
Hi,

We have an issue certificate. We have informed to our internal team. We will let you know as soon as we get an update.

Thanks,
Sruthi

**Comment by ADPMarketplace** [comment]
Hi,

Please let us know if you need any further assistance?

Thanks,
Sruthi

**Comment by awdee** [comment]
Hi @ADPMarketplace - Sruthi,

Can i use the cert.pem for connection?

Thanks

**Comment by ADPMarketplace** [comment]
Hi,

No, you can't because key file is mandatory. You can use .pfx directly because it is combination of .pem and .key file.

Thanks,
Sruthi
