### ISSUE TITLE
Just cloned solution fails

### ISSUE THREAD

**Issue by CGarvizu** [adplabs/adp-connection-NET#19]
The solution seems to work well when connecting to our service, yet the actual "demo" environment (https://iat-api.adp.com and https://iat-accounts.adp.com) throws an error when PostAsync is used:

ADPApiConnection.cs 
Line 311: response = client.PostAsync(url, content).Result;

I know it should not matter because our service works, yet a vendor is checking its implementation of OAuth for us, and they are using this site to test.

**Comment by ADPMarketplace** [comment]
Hi,

Can you please elaborate on the issue and please let us know what exact error are you seeing.

Thanks,
Sahithi Reddy

**Comment by CGarvizu** [comment]
Good morning,

Testing the demo apps failed even after just downloading the solution (no changes).

After reviewing the code and calls (Wireshark), we discovered that ADP is using TLS 1.2 to negotiate the connection, and the code (because the computers are configured that way) is still using TLS 1.0.

Although the recommendation is to use the operating system setting, we temporarily "hard-coded" the TLS 1.2 protocol before making the actual PostAsync call:

`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12 | System.Net.SecurityProtocolType.Tls11`

Regards.
