### ISSUE TITLE
HttpClient Exception

### ISSUE THREAD

**Issue by danielbeast** [adplabs/adp-connection-NET#20]
With the recent updates to WFN on 7/13, I was getting SSL/TLS exceptions from HttpClient. I added a line in SendWebRequest to choose TLS 1.2 first and no issues after that.

System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

**Comment by ADPMarketplace** [comment]
Hi Daniel,

We will review our code and get back to you.

Thanks,
Sahithi Reddy

**Comment by ComradeSlice** [comment]
I just encountered this problem. iat-api.adp.com only supports TLS 1.2. On my platform ServicePointManager's SecurityProtocolType defaults to Ssl3 | Tls (the latter being TLS 1.0). @ADPMarketplace what was the result of your review?
