### ISSUE TITLE
Production- invalid_redirect_uri / Mismatching redirect_uri.

### ISSUE THREAD

**Issue by bhavikmit** [adplabs/adp-connection-NET#21]
I am connecting to ADP workforce using below prod credentials from End-User Application.

{
"clientID": "XXXXXXXX-9f41-4676-b8cf-c63d53cd91d2",
  "clientSecret": "XXXXXXXX-f0da-40f1-a8bd-d2251367ba11",
          "sslCertPath": "~/Content/certs/Workhorse.pfx",
          "sslKeyPath": "~/Content/certs/Workhorse.key",
          "sslKeyPass": "************",
          "tokenServerURL": "https://api.adp.com/auth/oauth/v2/token",
          "disconnectURL": "https://accounts.adp.com/auth/oauth/v2/logout",
          "apiRequestURL": "https://api.adp.com",
          "baseAuthorizationURL": "https://accounts.adp.com/auth/oauth/v2/authorize",
          "redirectURL": "http://localhost:8889/callback",
          "accessScope": "hr.workerInformationManagement.workerManagement.workerViewing.worker.read hr.workerInformationManagement.workerManagement.associateManagment.associate.read hr.workerInformationManagement.workerManagement.employeeManagement.employee.read",
          "responseType": "code",
          "scope": "openid",
          "defaultexpiration": 3600,
          "grantType": "authorization_code"
          }

But I am getting an error like invalid_redirect_uri / Mismatching redirect_uri. 

![SLNjekxJAH](https://user-images.githubusercontent.com/11515257/65134351-c8d9be80-da21-11e9-91f5-64999be16cdb.gif)

Do I need to set redirectURL in adp portal? 

Can you please help me to what's the wrong configuration in this?

**Comment by ADPMarketplace** [comment]
Hi,

I see from the screenshot that you have provide below, you are logging into iat-accounts.adp.com end point but according to your message you have provided a production end point. The client credentials that you are using are production B2B application credentials but you are using them for B2C application.

Thanks,
Sahithi Reddy
