### ISSUE TITLE
redirectURL confusion.

### ISSUE THREAD

**Issue by bhavikmit** [adplabs/adp-connection-NET#23]
I have checked the code for asp-connection-Net End-User application, and I have confused about to how ADP maintains redirect URL.

Will it work with localhost-HTTPS?

For Different ClientId and Secret Id, Will it different? 

Because in some credentials, one redirect URL is working, and for another, it's not.

Also, some of the credentials I am getting an error like "Invalid redirect uri".

Do I need to set up redirect URL from ADP Portal?

I have explored the websites but not found any proper documentation for it.

**Comment by ADPMarketplace** [comment]
Hi,

If you need a customized URL we would setup that for you. The one that is there in github is just for testing purposes. You would require different client credentials, you cannot use the same.

Thanks,
Sahithi Reddy
