### ISSUE TITLE
Running the sample app password not working

### ISSUE THREAD

**Issue by mi-mclancy** [adplabs/adp-connection-NET#24]
Hi,

I downloaded the repo and tried to run the simple app and the username (MKPLDEMO) and password (marketplace1) are not working.

Please advise.

Thanks!

**Comment by ADPMarketplace** [comment]
Hi,

What is the error you are receiving?

Thanks,
Partner Enablement, ADP Marketplace

**Comment by mi-mclancy** [comment]
Hi,

I am getting an invalid username / password.

**Comment by ADPMarketplace** [comment]
Hi,

The password has been reset to "marketplace1". Can you please try now?

ADP Marketplace Partner Enablement

**Comment by mi-mclancy** [comment]
Hi,

It is working now. Thanks!
