### ISSUE TITLE
invalid_redirect_uri

### ISSUE THREAD

**Issue by bhavikmit** [adplabs/adp-connection-NET#25]
I am trying to connect ADO login page with below credentials but getting  an error like 'invalid_redirect_uri'

{
"clientID": "xxxxxxxx-9f41-4676-b8cf-c63d53cd91d2",
  "clientSecret": "xxxxxxxx-f0da-40f1-a8bd-d2251367ba11",
          "sslCertPath": "~/Content/certs/Workhorse.pfx",
          "sslKeyPath": "~/Content/certs/Workhorse.key",
          "sslKeyPass": "xxxxxxxxxxxxxx",
          "tokenServerURL": "https://api.adp.com/auth/oauth/v2/token",
          "disconnectURL": "https://accounts.adp.com/auth/oauth/v2/logout",
          "apiRequestURL": "https://api.adp.com",
          "baseAuthorizationURL": "https://accounts.adp.com/auth/oauth/v2/authorize",
          **"redirectURL": "https://wakemed-new.dev.myshiftwizard.com/adp/callback",**
          "accessScope": "hr.workerInformationManagement.workerManagement.workerViewing.worker.read hr.workerInformationManagement.workerManagement.associateManagment.associate.read hr.workerInformationManagement.workerManagement.employeeManagement.employee.read",
          "responseType": "code",
          "scope": "openid",
          "defaultexpiration": 3600,
          "grantType": "authorization_code"
          }

Also, I would like to allow below URLS for receive callback.
1. https://wakemed-new.dev.myshiftwizard.com/adp/callback
2. https://localhost:44390/adp/callback
3. https://localhost/adp/callback

Please help me on this issue.

**Comment by ADPMarketplace** [comment]
Hi,

The set of credentials used here are setup to use a specific redirectURL only. This repository only acts as a sandbox which can be used for testing. 

Thanks,
Partner Enablement, ADP Marketplace

**Comment by ADPMarketplace** [comment]
Request #184003 "Contact app support" was closed and merged into this request. Last comment in request #184003:

I am trying to connect ADO login page with below credentials but getting  an error like 'invalid_redirect_uri'

What does this error message mean? and How can I resolve it?

Here is the configuration I am using

{
"clientID": "xxxxxxxx-9f41-4676-b8cf-c63d53cd91d2",
  "clientSecret": "xxxxxxxx-f0da-40f1-a8bd-d2251367ba11",
          "sslCertPath": "~/Content/certs/Workhorse.pfx",
          "sslKeyPath": "~/Content/certs/Workhorse.key",
          "sslKeyPass": "xxxxxxxxxxxxxx",
          "tokenServerURL": "https://api.adp.com/auth/oauth/v2/token",
          "disconnectURL": "https://accounts.adp.com/auth/oauth/v2/logout",
          "apiRequestURL": "https://api.adp.com",
          "baseAuthorizationURL": "https://accounts.adp.com/auth/oauth/v2/authorize",
          **"redirectURL": "https://wakemed-new.dev.myshiftwizard.com/adp/callback",**
          "accessScope": "hr.workerInformationManagement.workerManagement.workerViewing.worker.read hr.workerInformationManagement.workerManagement.associateManagment.associate.read hr.workerInformationManagement.workerManagement.employeeManagement.employee.read",
          "responseType": "code",
          "scope": "openid",
          "defaultexpiration": 3600,
          "grantType": "authorization_code"
          }

Also, I would like to allow below URLS for receive callback.


1. https://wakemed-new.dev.myshiftwizard.com/adp/callback
2. https://localhost:44390/adp/callback
3. https://localhost/adp/callback

Please help me on this issue.

**Comment by bhavikmit** [comment]
@ADPMarketplace @ADPMarketplace 

I don't know why you closed this issue.

Do you mean this code is not valid for Production? Is it only for Sandbox?

My question is how can I resolved redirect URL issue for above configuration.

How can I change my redirect URL?

**Comment by ADPMarketplace** [comment]
Hi,

We have assigned one of our Partner Integration team member - Navin to assist you with this issue. He will be reaching out to you on this. Please feel free to get back to us if you haven't heard back.

Thanks,
Kirthi Priya Debbadi.
