### ISSUE TITLE
API rejecting valid certificate

### ISSUE THREAD

**Issue by Wchamberlin** [adplabs/adp-connection-NET#28]
Hello,

My company has recently acquired access to ADP APIs. After doing some preliminary testing within Postman I attempted to use this project to begin building a .NET solution using the ADP APIs. 

The only alterations I have made to the source project is to update the security protocol (TLS1.2) and to use our ClientID/Secret/Certificate file (That same values/files that worked when testing with Postman).

Attempting to run the 'ADPClientDemo' project with these settings to get an access token, the API simply spits back a 401 authentication error stating "proper client ssl certificate was not presented"

Any help would be appreciated.

**Comment by ADPMarketplace** [comment]
Wchamberlin-

Can you share the correlation ID of the error you are seeing? A correlation ID can be retrieved from the response headers of the API call.
