### ISSUE TITLE
Issue for accessing hr/v1/corporate-contacts

### ISSUE THREAD

**Issue by Chandakmanish04** [adplabs/adp-connection-NET#30]
When we are trying to access : hr/v1/corporate-contacts in it showing error : 
"scope for this service is invalid or undefined"
meanwhile if we try to access hr/v2/workers its working for us.

**Comment by ADPMarketplace** [comment]
Hi,

Can you provide the correlation ID of the error to us?

Thanks,
Kirthi

**Comment by Chandakmanish04** [comment]
Correlation Id is : 50690f5b-96914d17-b3a0639893bed0e5
With error code 403, forbidden

**Comment by ADPMarketplace** [comment]
We dont see any logs with the correlation ID you have provided. Are you an existing client to ADP?

**Comment by Chandakmanish04** [comment]
Yes, we are existing client for ADP. 
Please find attached screenshot for your reference.
![20200224_230438](https://user-images.githubusercontent.com/59999594/75228092-77eea300-57d5-11ea-93a5-f2e63786a716.jpg)

**Comment by ADPMarketplace** [comment]
We see that you do not have access to this API due to which you are seeing this error. Please reach out to your ADP Account Representative who has initially provided you with API access for adding this scope.

**Comment by Chandakmanish04** [comment]
We are having Workforce Now as ADP product, looks like it doesn't support call to "hr/v1/corporate-contacts" end point as per documentation we have received, to filter employee based on there name which end point we should be using.
Thank You

**Comment by ADPMarketplace** [comment]
Hi,

As of now there is no API which supports a filter to to retrieve a worker based on their name. 

Thanks,
Kirthi
