### ISSUE TITLE
test login does not work

### ISSUE THREAD

**Issue by camick2013** [adplabs/adp-connection-NET#4]
I ran the program and tried the login info "ADP username (MKPLDEMO) and password (marketplace1)". I received Login failed invalid username or password.

**Comment by ADPMarketplace** [comment]
Please try again with the same User ID and Password. The login should be working now.

**Comment by bhavikmit** [comment]
@ADPMarketplace is it changed again? Can't login with MKPLDEMO:marketplace1 with this demo code.

Thanks in advance!!
