### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by camick2013** [adplabs/adp-connection-NET#5]
Is there some other location that I can see the API documentation on what resources are available and the correct URLs? I have tried a couple found here [https://developers.adp.com/articles/api/all/apiexplorer](url). Some work, some don't.

For instance, I can access worker information like this.
`
try
{
	String str = connection.getADPData(connection.connectionConfiguration.apiRequestURL + "/hr/v2/workers?limit=5");
	Console.WriteLine("\r\nData: {0} ", str);
}
`

I grabbed those 5 associateIds and tried to get the time entry details like this.
`
try
{
	string[] associateId = new string[] { "G3QJ7HF98186MECX", "G3QJ7HF981866HK4", "G3QJ7HF98186T52H", "G3CC3TZ66CM78HZ4", "G3CC3TZ66CM7RYXT" };
	foreach (var id in associateId)
	{
	    string url = String.Format("{0}/get/time/v1/workers/{1}/time-entry-details", connection.connectionConfiguration.apiRequestURL, id);

	    try
	    {
		String str = connection.getADPData(url);
		Console.WriteLine("\r\nData: {0} ", str);
	    }
	    catch (Exception ex)
	    {
		string msg = String.Format("ID: {0}{1}Error: {2}", id, Environment.NewLine, ex.Message);
		Console.WriteLine(msg);
	    }
	}
}
`

But it throws a "not found" error on that url. I tried switching it to v2, but same error.

**Comment by camick2013** [comment]
Sorry I keep trying to format the code blocks so they read better, but it's not working.

**Comment by ADPMarketplace** [comment]
The Developer Library is associated with a consumer application that only has access to the Worker API. To get access to additional APIs, you will need to be an ADP client or a Marketplace partner.
