### ISSUE TITLE
Paging functionality

### ISSUE THREAD

**Issue by pbburkhalter** [adplabs/adp-connection-NET#6]
Is creating asynchronous worker calls included in this library, as it is referenced in the ADP documents provided by our account reps. If not, can it be added? I need to query more than 50 employees at a time.

**Comment by ADPMarketplace** [comment]
The asynchronous pattern is not included in this library; however, you can paginate through a collection of workers by using the $top and $skip OData query parameters. You can read more about OData on our Developer Portal: https://developers.adp.com/articles/general/open-data-protocol
