### ISSUE TITLE
How could we get Annual Salary

### ISSUE THREAD

**Issue by PaulZhou2018** [adplabs/adp-connection-NET#9]
Hi there,

How could we get Annual Salary through the API? So far we could get Pay Rate & Gross Pay; but none of them serves our needs. Also is there a W2 amount for the previous year?

Thanks a lot,
Paul

**Comment by ADPMarketplace** [comment]
Hi Paul,
Could you please help us understand to which product you belong to? so that we can help you with your queries accordingly.

Thanks,
Mahesh

**Comment by PaulZhou2018** [comment]
Hi Mahesh,

Below are URL'swe used in our code to retrieve data: 

"tokenServerURL": "https://accounts.adp.com/auth/oauth/v2/token"
"disconnectURL": "https://accounts.adp.com/auth/oauth/v2/logout"
"apiRequestURL": "https://api.adp.com"

Hope that would answer your question.

Thanks,
Paul

**Comment by ADPMarketplace** [comment]
Hi Paul,

Thank you for sharing the information, but we're actually looking for which type of ADP product( WFN\Vantage\Run) you're using. 

As you're already able to retrieve the data "Pay Rate & Gross Pay" through ADP APIs, you're an existing client to ADP. 

Someone from ADP has helped you getting the initial setup to consume ADP APIs, so it's someone from above mentioned 
products(WFN\Vantage\Run) is the best person who can help you getting the information you're looking for. 

Requesting you please get in touch with that person. If you still don't get any assistance, please come back to us, we're happy to help you.

Thanks,
Mahesh

**Comment by ADPMarketplace** [comment]
Hi Paul,
We discussed with WFN team and got to know that "Annual Salary" is not supported at the moment through API. 

Thanks,
Mahesh
